# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 73c7506b0a65f80b6a82b37b4bd2d437189156d2bcddefbeb6b73a5f1352de7cd26c7c29bd98c5ff4ec12dbbeb6e6c73b8783d77c9c5808062e694b0b63eb4d2

test:
  secret_key_base: 54b64bd1bd407f723c5786345145a12fcb423867ec5069832f2ab0871148dac87ebf710990a52e65a1465bda0959d4caa47bc6e21b4eb0f0d6ed835d096132d4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
